name: Testes Automatizados Cypress

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Configuração do Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalação das Dependências
        run: npm install

      - name: Puxar a Imagem Docker
        run: docker pull wlsf82/gitlab-ce

      - name: Iniciar Aplicação Docker
        run: docker run --publish 80:80 --publish 22:22 --hostname localhost wlsf82/gitlab-ce

      - name: Esperar a Inicialização
        run: sleep 30s # Espere tempo suficiente para a aplicação inicializar, você pode ajustar conforme necessário

      - name: Execução dos Testes Cypress
        run: npm run test
