name: Testes Automatizados Cypress

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Configuração do Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalação das Dependências
        run: npm install

      - name: Iniciar Aplicação Docker em Segundo Plano
        run: docker run --detach --publish 80:80 --publish 2222:22 --hostname localhost wlsf82/gitlab-ce

      - name: Esperar a Inicialização
        run: sleep 10s # 

      - name: Execução dos Testes Cypress
        run: npm run test
